baseURL = 'https://oldrusty.io/'
languageCode = 'en-gb'
title = 'OldRusty'
theme = "terminal"
disqusShortname = 'oldrusty'

[params]
centerTheme = true
themeColor = "orange"
contentTypeName = "p"

[languages]
  [languages.en]
    languageName = "English"
    title = "OldRusty"
    subtitle = "Musings of a dude learning rust"
    owner = "Richard Bagshaw"
    keywords = "Richard Bagshaw"
    copyright = "Content by Richard Bagshaw Â© 2022"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "OldRusty - a journey with Rust"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "table-of-contents"
        name = "Table of Contents"
        url = "/table-of-contents"
